### ISSUE TITLE
Test: error "disconnected with no message in 30000 ms"

### ISSUE THREAD

**Issue by softdays** [lit/lit-element-starter-js#4]
Environment: 
- Windows 10 x64
- NodeJS v12.18.1
- NPM 6.14.5

Steps to reproduce:
- `git clone https://github.com/PolymerLabs/lit-element-starter-js.git` 
- `cd lit-element-starter-js`
- `npm i`
- `npm test`

Error: 
```
> karma start karma.conf.cjs

START:
21 06 2020 09:21:33.530:WARN [filelist]: Pattern "D:/dev/projects/lit-element-starter-js/__snapshots__/**/*.md" does not match any file.
21 06 2020 09:21:33.579:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
21 06 2020 09:21:33.580:INFO [launcher]: Launching browsers ChromeHeadlessNoSandbox with concurrency unlimited
21 06 2020 09:21:33.593:INFO [launcher]: Starting browser ChromeHeadless
21 06 2020 09:21:34.346:INFO [HeadlessChrome 83.0.4103 (Windows 10.0.0)]: Connected on socket CGAMdeTrX3SAPk6vAAAA with id 27189707
21 06 2020 09:22:04.348:WARN [HeadlessChrome 83.0.4103 (Windows 10.0.0)]: Disconnected (0 times), because no message in 30000 ms.
HeadlessChrome 83.0.4103 (Windows 10.0.0) ERROR
  Disconnected, because no message in 30000 ms.
21 06 2020 09:22:04.353:WARN [framework.snapshot]: Snapshot data is unavailable

Finished in 30.002 secs / 0 secs @ 09:22:04 GMT+0200 (GMT+02:00)
```

Many thanks for your help

**Comment by leegee** [comment]
Same OS, same problem. Not a great advertisement for lit-element....

**Comment by leegee** [comment]
Is this library even maintained?

**Comment by AndrewJakubowicz** [comment]
Thanks for the report! Could you check if you get the same issue with node 14?

When using your env settings I get a different error:
```
npm run test

> @lit/lit-starter-js@0.0.0 test
> wtr

(node:16192) ExperimentalWarning: The ESM module loader is experimental.
SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:88:18)
    at async link (internal/modules/esm/module_job.js:41:21)
```

Maybe that is the error that causes the timeout?
@rictic Is there an explicit minimum supported Node version?

I cannot reproduce any issues with the following environment:
Windows 10 x64
NodeJS v14.14.0
NPM 7.8.0

**Comment by leegee** [comment]
Looking better now:
```

leege@studio MINGW64 /l/src/lit-element-test
$ git clone git@github.com:PolymerLabs/lit-element-starter-js.git .
Cloning into '.'...
remote: Enumerating objects: 185, done.
remote: Counting objects: 100% (185/185), done.
remote: Compressing objects:  51% (57/110) eceiving objects:   0remote: Compressing objects:  53% (59/110)
remote: Compressing objects:  54% (60/110) eceiving objects:   2remote: Compressing objects:  56% (62/110) eceiving objects:   3remote: Compressing objects:  58% (64/110) eceiving objects:   4remote: Compressing objects:  61% (68/110) eceiving objects:   5remote: Compressing objects:  63% (70/110) eceiving objects:   6remote: Compressing objects:  64% (71/110)Receiving objects:   7remote: Compressing objects:  77% (85/110)R
remote: Compressing objects:  79% (87/110)R
remote: Compressing objects:  81% (90/110)eceiving objects:  10%remote: Compressing objects:  82% (91/110)Receiving objects:  11remote: CompressRing objects:  83% (92/110)
remote: Compressing objects:  84% (93/110)
remote: Compressing objects:  85% (94/110)Receiving objects:  15remote: Compressing objects:  86% (95/110) eceiving objects:  16remote: Compressing objects:  88% (97/110)eceiving objects:  17%remote: Compressing objects:  89% (98/110)Receiving objects:  18remote: Compressing objects:  91% (101/110)
remote: Compressing objects:  92% (102/110)
remote: Compressing objects:  93% (103/110)Receiving objects:  2remote: Compressing objects:  94% (104/110) eceiving objects:  2remote: Compressing objects:  95% (105/110)Receiving objects:  2remote: Compressing objects:  98% (108/110)
remote: Compressing objects:  99% (109/110) eceiving objects:  3Remote: Compressing objects: 100% (110/110), done.
remote: Total 185 (delta 80), reused 150 (delta 56), pack-reusedReceiving objects: 100% (185/185)5)
Receiving objects: 100% (185/185), 424.91 KiB | 1.55 MiB/s, done.
Resolving deltas: 100% (80/80), done.

leege@studio MINGW64 /l/src/lit-element-test (master)
$ npm i
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.       
npm WARN deprecated flat@4.1.0: Fixed a prototype pollution security issue in 4.1.0, please upgrade to ^4.1.1 or ^5.0.1.
npm WARN deprecated fsevents@2.1.2: "Please update to latest v2.3 or v2.2"
npm WARN deprecated har-validator@5.1.3: this library is no longer supported
npm WARN deprecated mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

> playwright@1.8.1 install L:\src\lit-element-test\node_modules\playwright
> node install.js

Downloading chromium v844399 - 91 Mb [====================] 100% 0.0s
chromium v844399 downloaded to C:\Users\leege\AppData\Local\ms-playwright\chromium-844399
Downloading firefox v1225 - 75.1 Mb [====================] 100% 0.0s
firefox v1225 downloaded to C:\Users\leege\AppData\Local\ms-playwright\firefox-1225
Downloading webkit v1423 - 38.2 Mb [====================] 100% 0.0s
webkit v1423 downloaded to C:\Users\leege\AppData\Local\ms-playwright\webkit-1423

> core-js-bundle@3.10.2 postinstall L:\src\lit-element-test\node_modules\core-js-bundle
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> ejs@2.7.4 postinstall L:\src\lit-element-test\node_modules\ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

npm WARN rollup-plugin-summary@1.2.3 requires a peer of chalk@^4.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN rollup-plugin-summary@1.2.3 requires a peer of rollup-plugin-filesize@^9.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN sinon-chai@3.5.0 requires a peer of sinon@>=4.0.0 <10.0.0 but none is installed. You must install peer dependencies yourself.npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\@web\test-runner\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\@web\test-runner-core\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\@11ty\eleventy\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\karma\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\browser-sync\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\@open-wc\building-utils\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1567 packages from 1782 contributors and audited 1580 packages in 387.368s

72 packages are looking for funding
  run `npm fund` for details

found 4 vulnerabilities (1 low, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details

leege@studio MINGW64 /l/src/lit-element-test (master)
$ npm test

> @lit/lit-starter-js@0.0.0 test L:\src\lit-element-test
> wtr


test\my-element_test.js:

 ❌ page.goto: Couldn't resolve host name
=========================== logs ===========================
navigating to "http://localhost:8000/?wtr-session-id=d5d3ac33-894a-46aa-9ef0-9edd6eab9bab", waiting until "load"
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.  (failed on Webkit)
    page.goto: Couldn't resolve host name
    =========================== logs ===========================
    navigating to "http://localhost:8000/?wtr-session-id=d5d3ac33-894a-46aa-9ef0-9edd6eab9bab", waiting until "load"
    ============================================================
    Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
        at Connection.sendMessageToServer (L:\src\lit-element-test\node_modules\playwright\lib\client\connection.js:69:15)
        at Proxy.<anonymous> (L:\src\lit-element-test\node_modules\playwright\lib\client\channelOwner.js:44:61)
        at L:\src\lit-element-test\node_modules\playwright\lib\client\frame.js:80:71
        at Frame._wrapApiCall (L:\src\lit-element-test\node_modules\playwright\lib\client\channelOwner.js:72:34)
        at Frame.goto (L:\src\lit-element-test\node_modules\playwright\lib\client\frame.js:78:21)
        at L:\src\lit-element-test\node_modules\playwright\lib\client\page.js:270:60
        at Page._attributeToPage (L:\src\lit-element-test\node_modules\playwright\lib\client\page.js:205:20)
        at Page.goto (L:\src\lit-element-test\node_modules\playwright\lib\client\page.js:270:21)
        at PlaywrightLauncherPage.runSession (L:\src\lit-element-test\node_modules\@web\test-runner-playwright\dist\PlaywrightLauncherPage.js:24:35)
        at async PlaywrightLauncher.startSession (L:\src\lit-element-test\node_modules\@web\test-runner-playwright\dist\PlaywrightLauncher.js:52:9)

Chromium: |██████████████████████████████| 1/1 test files | 5 passed, 0 failed
Firefox:  |██████████████████████████████| 1/1 test files | 5 passed, 0 failed
Webkit:   |██████████████████████████████| 1/1 test files | 0 passed, 0 failed

Error while running tests.

npm ERR! Test failed.  See above for more details.

$ npm -v
6.14.11
$ node -v
v14.16.0


L:\src\lit-element-test>ver

Microsoft Windows [Version 10.0.19041.928]
```

**Comment by rictic** [comment]
Generally our minimum supported node version is whatever is the earliest LTS version of node that the node folks support. Not sure if we have a different policy for this repo in particular, but I'm guessing not.

**Comment by leegee** [comment]
Can't this now be closed? See above output

**Comment by AndrewJakubowicz** [comment]
Closing this as resolved. Please re-open or file a new issue if this problem persists. Thank you!
